on:
  workflow_dispatch:

name: Create artifacts

jobs:
  build:
    name: Create artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build --scan
      - name: Run ls
        run: ls -laR
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-build
          path: |
            USBMidiAndroid\build\outputs\
